### ISSUE TITLE
Elasticsearch error: "document already exists"

### ISSUE THREAD

**Issue by mykolasmith** [spotify/heroic#119]
Hi,

I'm seeing this error quite often being returned from the Heroic HTTP API. Example:

`{"message":"[heroic-1464825600000][1] [series][b5a903eb9726102bf3fb620392d26e00]: document already exists","reason":"Internal Server Error","status":500,"type":"internal-error"}`

If I retry the request, it usually returns a 200 straight away. I am wondering if firing concurrent POST requests at the same time (for new metrics) is sending duplicate metadata creation requests to the Elasticsearch API?

**Comment by udoprog** [comment]
We maintain a cache in the consumer process of which documents have previously been written, and each time it is started or entries time out we attempt to write the same document (with the same ID) again. This has so far worked and we get a code indicating that it was a duplicate, it should not be an issue as far as I know. I have not seen this in our logs before, but we use a different ingestion method (kafka-based).

Which version of Elasticsearch do you use? It should be possible to reproduce this by disabling the write cache.

**Comment by mykolasmith** [comment]
Yes, correct, we are using the HTTP endpoint. Some things to note

* Occurs whether the service has just been restarted or has been active for weeks.
* Occurs even when no new metrics / tag combinations have are being written (i.e. new points with existing metrics / tags)

In the Heroic access logs, we'll see a few messages at a time return 500 Internal Server Error:

```
10.4.0.167 - - [08/Nov/2016:20:26:45 +0000] "POST //heroic.[REDACTED]/write HTTP/1.1" 500 179
10.4.0.167 - - [08/Nov/2016:20:26:45 +0000] "POST //heroic.[REDACTED]/write HTTP/1.1" 500 177
```

In the Heroic main logs, we'll see a corresponding `org.elasticsearch.index.engine.DocumentAlreadyExistsException`:

```
2016-11-08 20:26:45,215 ERROR c.s.h.c.CoreJavaxRestFramework [elasticsearch[Jebediah Guthrie][listener][T#1]] Request failed org.elasticsearch.index.engine.DocumentAlreadyExistsException: [heroic-1478131200000][3] [metadata][fcaca5641390bf8084fed957c60bee87]: document already exists
	at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:329)
	at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:287)
	at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:259)
	at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:482)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:206)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2016-11-08 20:26:45,815 ERROR c.s.h.c.CoreJavaxRestFramework [qtp1576277927-19944] Request failed org.elasticsearch.index.engine.DocumentAlreadyExistsException: [heroic-1478131200000][1] [series][a25734a5b0c3c1d418582bc64eb7e8eb]: document already exists
	at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:329)
	at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:287)
	at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:259)
	at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:482)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:206)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mykolasmith** [comment]
Any progress on this? We're still seeing this error quite regularly (>1% of all requests to /write)

**Comment by udoprog** [comment]
No, this is not actively being worked on at the moment.
