### ISSUE TITLE
client=org.elasticsearch.client.node.NodeClient@429967c4) leaked @ unknown

### ISSUE THREAD

**Issue by servergeeks** [spotify/heroic#169]
Hi guys,

I've made an heroic cluster (4 nodes) that is using 5 cassandra nodes and 3 elasticsearch nodes.
For some reason after a day of ingesting data (around 2GB/index in ES), retrieving data becomes really slow and sometimes impossible...

If I try to do an HQL query in grafana I usually get to crash an heroic API node and everything stops working.

Any tips/ideas to improve performance and keep my cluster running/usable ? 

An example of an crash/error would be...

```
14:03:45.049 [nioEventLoopGroup-2-16] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000007 [new] grpc://heroic3.cc:1394
14:03:45.049 [nioEventLoopGroup-2-16] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000007 [new] grpc://heroic1.cc:1394
14:03:45.049 [nioEventLoopGroup-2-16] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000007 [new] grpc://heroic.cc:1394
14:03:45.049 [nioEventLoopGroup-2-16] ERROR com.spotify.heroic.cluster.CoreClusterManager - 00000007 [failed] grpc://heroic2.cc:1394
java.lang.RuntimeException: Request finished with status code (Status{code=DEADLINE_EXCEEDED, description=null, cause=null})
	at com.spotify.heroic.rpc.grpc.GrpcRpcClient$1.onClose(GrpcRpcClient.java:103)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:462)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
14:03:45.050 [nioEventLoopGroup-2-16] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000007 [update] [{site=HG}] 3 result(s)
14:04:17.843 [elasticsearch[heroic3][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service - [heroic3] removed {[heroic2][_QO3QHYpQs-2X4MXFbSX2Q][heroic2][inet[/131.1.1.7:9300]]{data=false, client=true},}, reason: zen-disco-receive(from master [[Occulus][H59ohQteSpGOQk1O69WCGA][heroic-e][inet[/131.1.1.2:9300]]])
14:04:17.845 [elasticsearch[heroic3][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service - [heroic3] removed {[heroic2][_QO3QHYpQs-2X4MXFbSX2Q][heroic2][inet[/131.1.1.7:9300]]{data=false, client=true},}, reason: zen-disco-receive(from master [[Occulus][H59ohQteSpGOQk1O69WCGA][heroic-e][inet[/131.1.1.2:9300]]])
14:04:45.050 [heroic-scheduler#0] INFO  com.spotify.heroic.cluster.CoreClusterManager - new refresh with id (00000008)
14:04:47.853 [elasticsearch[heroic3][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service - [heroic3] removed {[heroic2][kzCTkZdBRlqrGcBFKNahLQ][heroic2][inet[/131.1.1.7:9301]]{data=false, client=true},}, reason: zen-disco-receive(from master [[Occulus][H59ohQteSpGOQk1O69WCGA][heroic-e][inet[/131.1.1.2:9300]]])
14:04:47.855 [elasticsearch[heroic3][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service - [heroic3] removed {[heroic2][kzCTkZdBRlqrGcBFKNahLQ][heroic2][inet[/131.1.1.7:9301]]{data=false, client=true},}, reason: zen-disco-receive(from master [[Occulus][H59ohQteSpGOQk1O69WCGA][heroic-e][inet[/131.1.1.2:9300]]])
14:04:50.053 [nioEventLoopGroup-2-6] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000008 [new] grpc://heroic3.cc:1394
14:04:50.053 [nioEventLoopGroup-2-6] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000008 [new] grpc://heroic.cc:1394
14:04:50.054 [nioEventLoopGroup-2-6] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000008 [new] grpc://heroic1.cc:1394
14:04:50.054 [nioEventLoopGroup-2-6] ERROR com.spotify.heroic.cluster.CoreClusterManager - 00000008 [failed] grpc://heroic2.cc:1394
java.lang.RuntimeException: Request finished with status code (Status{code=DEADLINE_EXCEEDED, description=null, cause=null})
	at com.spotify.heroic.rpc.grpc.GrpcRpcClient$1.onClose(GrpcRpcClient.java:103)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:462)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
14:04:50.054 [nioEventLoopGroup-2-6] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000008 [update] [{site=HG}] 3 result(s)
14:05:50.055 [heroic-scheduler#4] INFO  com.spotify.heroic.cluster.CoreClusterManager - new refresh with id (00000009)

14:05:55.059 [nioEventLoopGroup-2-10] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000009 [new] grpc://heroic3.cc:1394
14:05:55.059 [nioEventLoopGroup-2-10] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000009 [new] grpc://heroic.cc:1394
14:05:55.059 [nioEventLoopGroup-2-10] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000009 [new] grpc://heroic1.cc:1394
14:05:55.059 [nioEventLoopGroup-2-10] ERROR com.spotify.heroic.cluster.CoreClusterManager - 00000009 [failed] grpc://heroic2.cc:1394
java.lang.RuntimeException: Request finished with status code (Status{code=DEADLINE_EXCEEDED, description=null, cause=null})
	at com.spotify.heroic.rpc.grpc.GrpcRpcClient$1.onClose(GrpcRpcClient.java:103)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:462)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
14:05:55.060 [nioEventLoopGroup-2-10] INFO  com.spotify.heroic.cluster.CoreClusterManager - 00000009 [update] [{site=HG}] 3 result(s)
14:06:55.060 [heroic-scheduler#2] INFO  com.spotify.heroic.cluster.CoreClusterManager - new refresh with id (0000000a)
14:07:00.063 [nioEventLoopGroup-2-15] INFO  com.spotify.heroic.cluster.CoreClusterManager - 0000000a [new] grpc://heroic3.cc:1394
14:07:00.063 [nioEventLoopGroup-2-15] INFO  com.spotify.heroic.cluster.CoreClusterManager - 0000000a [new] grpc://heroic.cc:1394
14:07:00.064 [nioEventLoopGroup-2-15] INFO  com.spotify.heroic.cluster.CoreClusterManager - 0000000a [new] grpc://heroic1.cc:1394
14:07:00.064 [nioEventLoopGroup-2-15] ERROR com.spotify.heroic.cluster.CoreClusterManager - 0000000a [failed] grpc://heroic2.cc:1394
java.lang.RuntimeException: Request finished with status code (Status{code=DEADLINE_EXCEEDED, description=null, cause=null})
	at com.spotify.heroic.rpc.grpc.GrpcRpcClient$1.onClose(GrpcRpcClient.java:103)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:462)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
14:07:00.064 [nioEventLoopGroup-2-15] INFO  com.spotify.heroic.cluster.CoreClusterManager - 0000000a [update] [{site=HG}] 3 result(s)
14:07:30.085 [jersey-background-task-scheduler-0] WARN  com.spotify.heroic.common.CoreJavaxRestFramework - Client timed out
14:07:30.085 [jersey-background-task-scheduler-0] ERROR com.spotify.heroic.common.CoreJavaxRestFramework - Request cancelled
14:07:30.089 [jersey-background-task-scheduler-0] INFO  org.eclipse.jetty.server.RequestLog - 131.130.249.44 - - [16/Dec/2016:13:02:30 +0000] "POST //heroic3.cc:8080/query/batch HTTP/1.1" 500 101 
14:07:30.090 [jersey-background-task-scheduler-0] WARN  com.spotify.heroic.common.CoreJavaxRestFramework - Client completed
14:07:43.525 [jersey-background-task-scheduler-0] WARN  com.spotify.heroic.common.CoreJavaxRestFramework - Client timed out
14:07:43.525 [jersey-background-task-scheduler-0] ERROR com.spotify.heroic.common.CoreJavaxRestFramework - Request cancelled
14:07:43.528 [jersey-background-task-scheduler-0] INFO  org.eclipse.jetty.server.RequestLog - 131.130.249.44 - - [16/Dec/2016:13:02:43 +0000] "POST //heroic3.cc:8080/query/batch HTTP/1.1" 500 101 
14:07:43.528 [jersey-background-task-scheduler-0] WARN  com.spotify.heroic.common.CoreJavaxRestFramework - Client completed
14:08:00.065 [heroic-scheduler#2] INFO  com.spotify.heroic.cluster.CoreClusterManager - new refresh with id (0000000b)
14:08:01.637 [nioEventLoopGroup-2-5] INFO  com.spotify.heroic.cluster.CoreClusterManager - 0000000b [new] grpc://heroic3.cc:1394
14:08:01.637 [nioEventLoopGroup-2-5] INFO  com.spotify.heroic.cluster.CoreClusterManager - 0000000b [new] grpc://heroic.cc:1394
14:08:01.637 [nioEventLoopGroup-2-5] INFO  com.spotify.heroic.cluster.CoreClusterManager - 0000000b [new] grpc://heroic1.cc:1394
14:08:01.637 [nioEventLoopGroup-2-5] INFO  com.spotify.heroic.cluster.CoreClusterManager - 0000000b [update] [{site=HG}] 4 result(s)
14:08:01.876 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], begin rebalancing consumer heroic_heroic3-1481892993532-faf9240b try #0
14:08:01.933 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1481892993640] Stopping leader finder thread
14:08:01.933 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherManager$LeaderFinderThread - [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread], Shutting down
14:08:01.933 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.consumer.ConsumerFetcherManager$LeaderFinderThread - [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread], Stopped 
14:08:01.933 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherManager$LeaderFinderThread - [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread], Shutdown completed
14:08:01.934 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1481892993640] Stopping all fetchers
14:08:01.934 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-1], Shutting down
14:08:01.934 [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-1] WARN  kafka.consumer.SimpleConsumer - Reconnect due to socket error: null
14:08:01.935 [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-1] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-1], Stopped 
14:08:01.935 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-1], Shutdown completed
14:08:01.935 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-3], Shutting down
14:08:01.936 [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-3] WARN  kafka.consumer.SimpleConsumer - Reconnect due to socket error: null
14:08:01.936 [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-3] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-3], Stopped 
14:08:01.937 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-3], Shutdown completed
14:08:01.937 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1481892993640] All connections stopped
14:08:01.937 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], Cleared all relevant queues for this fetcher
14:08:01.937 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], Cleared the data chunks in all the consumer message iterators
14:08:01.937 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], Committing all offsets after clearing the fetcher queues
14:08:01.940 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], Releasing partition ownership
14:08:01.944 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], Consumer heroic_heroic3-1481892993532-faf9240b rebalancing the following partitions: ArrayBuffer(0, 1, 2, 3, 4, 5, 6, 7, 8, 9) for topic metrics with consumers: List(heroic_heroic-1481893181613-f2c9267b-0, heroic_heroic-1481893181613-f2c9267b-1, heroic_heroic1-1481893140289-6988cffe-0, heroic_heroic1-1481893140289-6988cffe-1, heroic_heroic2-1481893050704-558be4ae-0, heroic_heroic2-1481893050704-558be4ae-1, heroic_heroic3-1481892993532-faf9240b-0, heroic_heroic3-1481892993532-faf9240b-1)
14:08:01.944 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], heroic_heroic3-1481892993532-faf9240b-0 attempting to claim partition 8
14:08:01.945 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], heroic_heroic3-1481892993532-faf9240b-1 attempting to claim partition 9
14:08:01.947 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], heroic_heroic3-1481892993532-faf9240b-0 successfully owned partition 8 for topic metrics
14:08:01.948 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], heroic_heroic3-1481892993532-faf9240b-1 successfully owned partition 9 for topic metrics
14:08:01.948 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], Updating the cache
14:08:01.948 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], Consumer heroic_heroic3-1481892993532-faf9240b selected partitions : metrics:8: fetched offset = 788121: consumed offset = 788121,metrics:9: fetched offset = 788111: consumed offset = 788111
14:08:01.949 [heroic_heroic3-1481892993532-faf9240b_watcher_executor] INFO  kafka.consumer.ZookeeperConsumerConnector - [heroic_heroic3-1481892993532-faf9240b], end rebalancing consumer heroic_heroic3-1481892993532-faf9240b try #0
14:08:01.951 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.consumer.ConsumerFetcherManager$LeaderFinderThread - [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread], Starting 
14:08:01.958 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.utils.VerifiableProperties - Verifying properties
14:08:01.958 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.utils.VerifiableProperties - Property client.id is overridden to heroic
14:08:01.959 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.utils.VerifiableProperties - Property metadata.broker.list is overridden to kafkabaer1.cc:9092,kafkabaer2.cc:9092,kafkabaer3.cc:9092
14:08:01.959 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.utils.VerifiableProperties - Property request.timeout.ms is overridden to 30000
14:08:01.959 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.client.ClientUtils$ - Fetching metadata from broker id:1,host:kafkabaer1.cc,port:9092 with correlation id 9 for 1 topic(s) Set(metrics)
14:08:01.959 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.producer.SyncProducer - Connected to kafkabaer1.cc:9092 for producing
14:08:01.960 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.producer.SyncProducer - Disconnecting from kafkabaer1.cc:9092
14:08:01.961 [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-1] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-1], Starting 
14:08:01.961 [heroic_heroic3-1481892993532-faf9240b-leader-finder-thread] INFO  kafka.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1481892993640] Added fetcher for partitions ArrayBuffer([[metrics,8], initOffset 788121 to broker id:3,host:kafkabaer3.cc,port:9092] , [[metrics,9], initOffset 788111 to broker id:1,host:kafkabaer1.cc,port:9092] )
14:08:01.962 [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-3] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-heroic_heroic3-1481892993532-faf9240b-0-3], Starting 
14:08:04.700 [elasticsearch[heroic3][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service - [heroic3] added {[heroic2][_QO3QHYpQs-2X4MXFbSX2Q][heroic2][inet[/131.1.1.7:9300]]{data=false, client=true},}, reason: zen-disco-receive(from master [[Occulus][H59ohQteSpGOQk1O69WCGA][heroic-e][inet[/131.1.1.2:9300]]])
14:08:04.701 [elasticsearch[heroic3][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service - [heroic3] added {[heroic2][_QO3QHYpQs-2X4MXFbSX2Q][heroic2][inet[/131.1.1.7:9300]]{data=false, client=true},}, reason: zen-disco-receive(from master [[Occulus][H59ohQteSpGOQk1O69WCGA][heroic-e][inet[/131.1.1.2:9300]]])
14:08:04.778 [elasticsearch[heroic3][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service - [heroic3] added {[heroic2][kzCTkZdBRlqrGcBFKNahLQ][heroic2][inet[/131.1.1.7:9301]]{data=false, client=true},}, reason: zen-disco-receive(from master [[Occulus][H59ohQteSpGOQk1O69WCGA][heroic-e][inet[/131.1.1.2:9300]]])
14:08:04.780 [elasticsearch[heroic3][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service - [heroic3] added {[heroic2][kzCTkZdBRlqrGcBFKNahLQ][heroic2][inet[/131.1.1.7:9301]]{data=false, client=true},}, reason: zen-disco-receive(from master [[Occulus][H59ohQteSpGOQk1O69WCGA][heroic-e][inet[/131.1.1.2:9300]]])
```

**Comment by valentinul** [comment]
This is another example of an leak
```
eu.toolchain.async.PrintStreamDefaultAsyncCaller: reference com.spotify.heroic.metric.datastax.Connection@53533fb5 leaked @ unknown
eu.toolchain.async.PrintStreamDefaultAsyncCaller: reference Connection(index=RotatingIndexMapping(interval=86400000, maxReadIndices=2, maxWriteIndices=1, pattern=heroic-%s), client=org.elasticsearch.client.node.NodeClient@429967c4) leaked @ unknown
```

**Comment by valentinul** [comment]
Ok...so it seems that my ES master fails at some point and disconnects the heroic nodes or something similar and makes this node to crash/quit.

More errors ...
```
14:48:41.427 [jersey-background-task-scheduler-0] WARN  com.spotify.heroic.common.CoreJavaxRestFramework - Client completed
14:48:57.257 [cluster1-nio-worker-0] WARN  com.datastax.shaded.netty.channel.nio.NioEventLoop - Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
14:49:00.874 [qtp1934692470-20] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - 
java.lang.OutOfMemoryError: GC overhead limit exceeded
14:49:00.874 [qtp1934692470-20] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@70582f0a in qtp1934692470{STARTED,8<=8<=200,i=4,q=0}
```

**Comment by valentinul** [comment]
The CPU usage is quite high on nodes when something like this happens ...
![heroic-usage](https://cloud.githubusercontent.com/assets/5860438/21265191/81e711de-c3a0-11e6-8931-97dea9f06bd8.png)

**Comment by udoprog** [comment]
Hey!

I need to know two things:

* Which commit of Heroic are you running?
* If you can enable the `-D eu.toolchain.async.Managed.trace=yes` system property it will cause stack traces to be captured and `@ unknown` should instead show us where the reference was leaked. You can encourage this to happen by triggering a gc through `jcmd <pid> GC.run` after you think the reference has been leaked.

**Comment by valentinul** [comment]
Hi,
Using (b32969792b5f85730d7b0a23a00e48d19097da9c) on all 4 nodes. 
The ES cluster is made out of 3 nodes (v1.7.6)
The kafka cluster is made out of 3 nodes (v0.10.1.0)
Using oracle java.
```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
Regarding the "-D eu.toolchain.async.Managed.trace=yes", I'm not sure where to enable/add it.

Thank you!

**Comment by valentinul** [comment]
Seems like the ES master runs out of memory and the ES cluster is masterless and that's causing the leaks in the heroic nodes...

```
[2016-12-19 09:52:25,080][DEBUG][action.index             ] [Occulus] [heroic-1481932800000][2], node[H59ohQteSpGOQk1O69WCGA], [P], s[STARTED]: Failed to execute [index {[heroic-1481932800000][tag][4c6d808e9ee6ef83147226e6c2bd22cd:7bcf49d4], source[{"key":"time-trans-934399859187491","tags":["database\u0000PROD","host\u0000ursa4.cc","type\u0000time-trans"],"tag_keys":["database","host","type"],"series_id":"4c6d808e9ee6ef83147226e6c2bd22cd","skey":"host","sval":"ursa4.cc","kv":"host\u0000ursa4.cc"}]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
Caused by: java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects

```

**Comment by valentinul** [comment]
Another issue would be this...

```
[2016-12-19 10:11:13,485][DEBUG][action.search.type       ] [Sigyn] [3] Failed to execute query phase
org.elasticsearch.transport.RemoteTransportException: [Fagin][inet[/131.1.1.2:9300]][indices:data/read/search[phase/scan/scroll]]
Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [3]
	at org.elasticsearch.search.SearchService.findContext(SearchService.java:537)
	at org.elasticsearch.search.SearchService.executeScan(SearchService.java:265)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:939)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:930)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by udoprog** [comment]
@valentinul to configure `-D eu.toolchain.async.Managed.trace=yes`, you add it as an argument when you invoke `java`.

If you are using the provided debian packaging, you can add it to a file next to the configuration with a `.jvmargs` suffix instead of `.yml`.

**Comment by valentinul** [comment]
@udoprog I was thinking the same but unfortunately it's complaining about class not found...

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
