### ISSUE TITLE
Error when getting Elasticsearch timeout

### ISSUE THREAD

**Issue by jo-ri** [spotify/heroic#175]
A timeout in Elasticsearch caused an error. Occurred while executing a long running ShellTask with a reference to MetricManager that didn't interact with Elasticsearch.

```
16:09:23.742 [elasticsearch[Scintilla][generic][T#27]] ERROR com.spotify.heroic.HeroicShell - Uncaught exception in thread Thread[elasticsearch[Scintilla][generic][T#27],5,main], exiting...
java.lang.NoClassDefFoundError: org/elasticsearch/transport/TransportService$TimeoutInfoHolder
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:524)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.transport.TransportService$TimeoutInfoHolder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```

**Comment by udoprog** [comment]
Possibly irrelevant when we move to new version of ES: #75
