### ISSUE TITLE
No more data returned by heroic

### ISSUE THREAD

**Issue by servergeeks** [spotify/heroic#213]
Hi guys,

I've done a git pull and package build and it seems that no more data is returned by heroic...

This is my git reflog 
```
root@heroic:~/heroic# git reflog --date=iso
a0551f6 HEAD@{2017-02-06 09:45:53 +0100}: pull: Fast-forward
be6c06f HEAD@{2016-12-22 12:46:06 +0100}: pull: Fast-forward
b329697 HEAD@{2016-12-16 12:02:38 +0100}: pull: Fast-forward
114d815 HEAD@{2016-12-15 13:01:43 +0100}: pull: Fast-forward
12b92c5 HEAD@{2016-12-05 10:00:04 +0100}: pull: Fast-forward
c6a43b0 HEAD@{2016-12-01 15:32:27 +0100}: pull: Fast-forward
51494af HEAD@{2016-11-28 16:27:42 +0100}: pull: Fast-forward
660e16e HEAD@{2016-11-14 14:21:20 +0100}: pull: Fast-forward
cf81df2 HEAD@{2016-11-03 13:53:35 +0100}: pull: Fast-forward
c05e7dc HEAD@{2016-10-14 10:12:40 +0200}: pull: Fast-forward
2a16276 HEAD@{2016-10-13 11:37:22 +0200}: pull: Fast-forward
240076d HEAD@{2016-10-11 09:20:06 +0200}: pull: Fast-forward
6986d65 HEAD@{2016-10-08 21:37:19 +0200}: pull: Fast-forward
f576768 HEAD@{2016-09-27 21:21:29 +0200}: pull: Fast-forward
1a3578c HEAD@{2016-09-01 21:29:47 +0200}: clone: from https://github.com/spotify/heroic.git
```
The errors seem to be coming from elasticsearch ...

```
[2017-02-06 14:05:05,602][DEBUG][action.search.type       ] [Achilles] [59813] Failed to execute query phase
org.elasticsearch.transport.RemoteTransportException: [Gauntlet][inet[/1.1.1.2:9300]][indices:data/read/search[phase/scan/scroll]]
Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [59813]
	at org.elasticsearch.search.SearchService.findContext(SearchService.java:537)
	at org.elasticsearch.search.SearchService.executeScan(SearchService.java:265)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:939)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:930)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I see the index for this respective day present in ES and the heroic api nodes seem the be able to consume and insert data in ES and cassandra normally. 

The retrievel of data returns the following message...

```
{"queryId":"edd112b3-8a66-4f62-8d14-dcb814e8ef87","range":{"start":1486386897275,"end":1486386902275},"trace":{"what":{"name":"com.spotify.heroic.CoreQueryManager#query"},"elapsed":738436,"children":[{"what":{"name":"com.spotify.heroic.CoreQueryManager#query_shard[{site=HG}]"},"elapsed":738552,"children":[]}]},"limits":[],"commonTags":{},"result":[],"errors":[{"type":"shard","nodes":["grpc://heroic1.cc:1394[local]#query","grpc://heroic.cc:1394#query","grpc://heroic3.cc:1394#query","grpc://heroic2.cc:1394#query"],"shard":{"site":"HG"},"error":"Request finished with status code (Status{code=UNKNOWN, description=null, cause=null}), caused by Request finished with status code (Status{code=UNKNOWN, description=null, cause=null})"}]}
```

**Comment by valentinul** [comment]
Any ideas ?

**Comment by udoprog** [comment]
The most common cause for not seeing data is a malconfigured metadata cluster.

You should do the usual rounds of troubleshooting:

```
$> tools/install-repackaged
$> mvn package -D maven.test.skip=true
$> tools/heroic-shell -C path/to/config.yaml
heroic> metadata-count
# should be non-zero
heroic> metadata-find
# should show some results
heroic> fetch --series '<series json>' --start -3600000 --end +0
# should show some data for the given series
heroic> query <your query as hql>
# should show results for the given query
```

These are taken from memory, so some of them might not be accurate.

I'm considering writing an F.A.Q. and adding these. It might also be worth adding a `troubleshoot` task that verifies that all clusters are correctly configured and can data and response to queries for future use.

**Comment by valentinul** [comment]
Hi John,
Thank you for the reply. 
Unfortunately there is still no data fetched/returned. 
This is the message when I do metadata-find. It looks like there is some operation stuck/running ?
```
heroic> metadata-find
Command Failed: java.lang.IllegalArgumentException: Too many (2) matching tasks (metadata-find-series, metadata-find-series-ids)
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Too many (2) matching tasks (metadata-find-series, metadata-find-series-ids)
	at eu.toolchain.async.immediate.ImmediateFailedAsyncFuture.get(ImmediateFailedAsyncFuture.java:117)
	at com.spotify.heroic.shell.ShellServerClientThread.doRun(ShellServerClientThread.java:104)
	at com.spotify.heroic.shell.ShellServerClientThread.run(ShellServerClientThread.java:60)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Too many (2) matching tasks (metadata-find-series, metadata-find-series-ids)
	at com.spotify.heroic.CoreShellTasks.resolveTask(CoreShellTasks.java:190)
	at com.spotify.heroic.CoreShellTasks.evaluate(CoreShellTasks.java:82)
	at com.spotify.heroic.shell.ShellServerClientThread$1.visitRunTaskRequest(ShellServerClientThread.java:91)
	at com.spotify.heroic.shell.ShellServerClientThread$1.visitRunTaskRequest(ShellServerClientThread.java:78)
	at com.spotify.heroic.shell.protocol.EvaluateRequest.visit(EvaluateRequest.java:36)
	at com.spotify.heroic.shell.ShellServerClientThread.doRun(ShellServerClientThread.java:101)
	... 2 more
time: 10.553 ms
heroic> metadata-count
Found 623 serie(s)
time: 17.764 ms
```

**Comment by udoprog** [comment]
Then you should use `metadata-find-series`.

**Comment by valentinul** [comment]
I ran metadata-find-series and it returns some records as expected but is data still not showing up in grafana or when using curl ?

**Comment by udoprog** [comment]
You should try to run the `fetch` as well as instructed in the first message, that one attempts to `fetch` data directly.

**Comment by valentinul** [comment]
I've executed the following but not return anything. Is the json structure that I'm using the correct one ? 

```
heroic> fetch --series '{"key":"soap","tags":{"host":"panda3.cc","name":"confirm_zone_deletion","source_ip":"131.1.2.3","type":"command"}}' --start -3600000 --end +0
TRACE:
com.spotify.heroic.metric.LocalMetricManager#fetch (in 2.977us)
  com.spotify.heroic.metric.datastax.DatastaxBackend#fetch (in 2.966us)
    com.spotify.heroic.metric.datastax.DatastaxBackend#fetch_segment (in 3.042us)
time: 6.301 ms
```

**Comment by udoprog** [comment]
It could be a regression in the Datastax backend. I'd recommend against upgrading until it has been disproved or fixed.

Could you tell me which commit you upgraded from?

**Comment by valentinul** [comment]
```
root@heroic:~/heroic# git reflog --date=iso
a0551f6 HEAD@{2017-02-06 09:45:53 +0100}: pull: Fast-forward  <- current
be6c06f HEAD@{2016-12-22 12:46:06 +0100}: pull: Fast-forward <- old one witch was working.

```

**Comment by udoprog** [comment]
Very little changed in relation to the datastax backend, could you verify that reverting back fixes the issue?

**Comment by valentinul** [comment]
Sure, I've done a git reset --hard be6c06f...
And now rebuilding deb packages..let's see how it goes..

**Comment by valentinul** [comment]
I've started the nodes now this kind of error shows up in the logs
```
11:42:48.815 [grpc-default-executor-1] ERROR com.spotify.heroic.rpc.grpc.GrpcRpcProtocolServer - Failed to handle request (sent Status{code=INTERNAL, description=null, cause=null})
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Boolean from String value ("default"): only "true" or "false" recognized
 at [Source: [B@76927b58; line: 1, column: 238] (through reference chain: com.spotify.heroic.rpc.grpc.GroupedQuery["query"]->com.spotify.heroic.metric.Request["options"]->com.spotify.heroic.QueryOptions["tracing"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1021)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseBoolean(StdDeserializer.java:213)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BooleanDeserializer.deserialize(NumberDeserializers.java:184)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BooleanDeserializer.deserialize(NumberDeserializers.java:167)
	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:90)
	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:13)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2907)
	at com.spotify.heroic.rpc.grpc.GrpcRpcProtocolServer.lambda$serverCallHandlerFor$16(GrpcRpcProtocolServer.java:219)
	at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:147)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:255)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:458)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by udoprog** [comment]
It looks like you are running mixed versions of a given node in the cluster, that is currently not possible since the internal RPC protocol is not stable.

**Comment by valentinul** [comment]
They all have the same config. Could one of them be running a different commit ?

**Comment by valentinul** [comment]
![screenshot from 2017-02-09 11-59-07](https://cloud.githubusercontent.com/assets/5860438/22780482/33df9ff2-eebf-11e6-9770-8bc4ce5038b4.png)
Yep...running the old commit seems to work.
