### ISSUE TITLE
hql date range

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#265]
hello 
i try to use
`
GET /render/image?q=average by f  from points where $key =nsa and host = "fslg" and range="" 
`
but i get 

```
Range must be present
04/05/2017 11:28:22	at com.spotify.heroic.CoreQueryManager$Group.lambda$buildRange$17(CoreQueryManager.java:335)
04/05/2017 11:28:22	at java.util.Optional.orElseThrow(Optional.java:290)
04/05/2017 11:28:22	at com.spotify.heroic.CoreQueryManager$Group.buildRange(CoreQueryManager.java:335)
```

i don' t know how to write daterange in HQL for get query ?
where is it in the code ? 
thanks

**Comment by udoprog** [comment]
```
average by f from points(1d)
```
or for absolute:
```
average by f from points(1000, 2000)
```

**Comment by lucilecoutouly** [comment]
thank you it works great
