### ISSUE TITLE
 Error querying cassandra:9042 : com.datastax.driver.core.exceptions.BusyPoolException: [cassandra] Pool is busy (no available connection and the queue has reached its max size 256)

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#324]
hello ,

it's related to #243 
when i do a big query:
```
 Error querying cassandraseed/10.42.28.96:9042 : com.datastax.driver.core.exceptions.BusyPoolException: [cassandraseed/10.42.28.96] Pool is busy (no available connection and the queue has reached its max size 256)
```
did you change the version of cassandra driver ?
how to prevent this error ?

some working in the hawkular time serie says:
BusyPoolException under heavy load - no available connection and the queue has reached its max size 256
https://issues.jboss.org/browse/HWKMETRICS-542
https://issues.jboss.org/browse/HWKMETRICS-597

is it related ??

is this a resolution : 
https://datastax-oss.atlassian.net/browse/JAVA-893

thanks

**Comment by udoprog** [comment]
Classifying this as a bug with the updated Cassandra driver.

We'll have to implement back-off internally (which is a bit of a pita). For now, if we patch the Cassandra module we can make the options mentioned here configurable:
http://docs.datastax.com/en/latest-java-driver-api/com/datastax/driver/core/exceptions/BusyPoolException.html
```
PoolingOptions.setMaxRequestsPerConnection(HostDistance, int): maximum number of requests per connection;
PoolingOptions.setMaxConnectionsPerHost(HostDistance, int): maximum number of connections in the pool;
PoolingOptions.setMaxQueueSize(int): maximum number of enqueued requests before this exception is thrown.
```

**Comment by lucilecoutouly** [comment]
how to patch the cassandra module  ?
are you planning it ?

**Comment by udoprog** [comment]
It would probably go in here:
https://github.com/spotify/heroic/blob/master/metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/ManagedSetupConnection.java

With options specified here:
https://github.com/spotify/heroic/blob/master/metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxMetricModule.java

Can't commit to adding the options right now, will have a look if I get some time. Otherwise, someone else can add it.

**Comment by lucilecoutouly** [comment]
hello 

i am trying to fix this issue but i don't understand : 

It would probably go in here:
https://github.com/spotify/heroic/blob/master/metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/ManagedSetupConnection.java

With options specified here:
https://github.com/spotify/heroic/blob/master/metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxMetricModule.java

could you explain a little bit what have i to do ?

thanks

**Comment by lucilecoutouly** [comment]
hello 

none of the parametters fix this issue 
when did you plan to fix this bug ?

thanks

**Comment by udoprog** [comment]
@lucilecoutouly did you bump the variables mentioned, and to what value did you set them?

**Comment by lucilecoutouly** [comment]
Here are some results

TEST
====


test RT 13/02/2013
cassandra 1 seed node
HEAP_NEWSIZE 16g
MAX_HEAP_SIZE 16g

Query :

```json
{'source': 'points', 'range': {'type': 'absolute', 'start': 1360717200000, 'end': 1360786200000}, 'filter': ['and', ['key', 'nsa']]} http://heroic:8080/query/metrics
```

* nothing restrict

```json
res query time : 45.19901132583618
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=f5207a32-2db4-404d-9208-8ffb77d8411b, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (80105) or were cancelled (0), caused by Some fetches failed (80105) or were cancelled (0)'}]

res query time : 17.484973430633545
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=f5207a32-2db4-404d-9208-8ffb77d8411b, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (14378) or were cancelled (0), caused by Some fetches failed (14378) or were cancelled (0)'}]

res query time : 20.715453147888184
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=b9641fc1-d51e-4515-ab82-73649ee7db07, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (16139) or were cancelled (0), caused by Some fetches failed (16139) or were cancelled (0)'}]
```

* pooling.setMaxRequestsPerConnection(HostDistance.REMOTE, 10);// maximum number of requests per connection;

```json
res query time : 44.065261363983154
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=0f5ec78d-abfa-40f6-ade1-19e46c0cae54, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (73736) or were cancelled (0), caused by Some fetches failed (73736) or were cancelled (0)'}]
res query time : 25.020118713378906
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=0f5ec78d-abfa-40f6-ade1-19e46c0cae54, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (41901) or were cancelled (0), caused by Some fetches failed (41901) or were cancelled (0)'}]
```


* pooling.setMaxConnectionsPerHost(HostDistance.REMOTE, 10);

```json
res query time : 22.83149790763855
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=70cb8d7c-9a19-4bed-99cc-8ef9ee5979f8, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (19989) or were cancelled (0), caused by Some fetches failed (19989) or were cancelled (0)'}]
res query time : 46.9206976890564
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=70cb8d7c-9a19-4bed-99cc-8ef9ee5979f8, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (84449) or were cancelled (0), caused by Some fetches failed (84449) or were cancelled (0)'}]
```

* pooling.setMaxRequestsPerConnection(HostDistance.REMOTE, 10);// maximum number of requests per connection;
* pooling.setMaxConnectionsPerHost(HostDistance.REMOTE, 10);//maximum number of connections in the pool;

```json
res query time : 59.644617319107056
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=48ba8b3c-7f97-4464-864d-0dc8f4fc61bd, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (80920) or were cancelled (0), caused by Some fetches failed (80920) or were cancelled (0)'}]
res query time : 24.001625537872314
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=48ba8b3c-7f97-4464-864d-0dc8f4fc61bd, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (36190) or were cancelled (0), caused by Some fetches failed (36190) or were cancelled (0)'}]
res query time : 51.34506320953369
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=48ba8b3c-7f97-4464-864d-0dc8f4fc61bd, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (81177) or were cancelled (0), caused by Some fetches failed (81177) or were cancelled (0)'}]
res query time : 36.39614748954773
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=7d84b55f-9c37-4478-a47e-8407e4a3b137, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (60594) or were cancelled (0), caused by Some fetches failed (60594) or were cancelled (0)'}]
```

* pooling.setMaxRequestsPerConnection(HostDistance.REMOTE, 10);// maximum number of requests per connection;
* pooling.setMaxConnectionsPerHost(HostDistance.REMOTE, 10);//maximum number of connections in the pool;
* pooling.setMaxQueueSize(10);

```json
res query time : 29.48314905166626
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=523ad1f1-4ab8-493f-86d5-d285d50d14fe, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (43400) or were cancelled (0), caused by Some fetches failed (43400) or were cancelled (0)'}]
```

* pooling.setMaxConnectionsPerHost(HostDistance.REMOTE, 100);//maximum number of connections in the pool;

```json
res query time : 16.266963720321655
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=f76696fa-2417-458e-a91f-1d179fbd05ab, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (1) or were cancelled (0), caused by Some fetches failed (1) or were cancelled (0)'}]
```

* pooling.setMaxConnectionsPerHost(HostDistance.LOCAL, 150);//maximum number of connections in the pool;
```json
res query time : 22.25321125984192
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=1391cda0-c443-4342-a723-4e648ed316aa, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (20588) or were cancelled (0), caused by Some fetches failed (20588) or were cancelled (0)'}]
res query time : 38.81354069709778
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=1391cda0-c443-4342-a723-4e648ed316aa, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (73905) or were cancelled (0), caused by Some fetches failed (73905) or were cancelled (0)'}]
```

* pooling.setMaxRequestsPerConnection(HostDistance.REMOTE, 10);// maximum number of requests per connection;
* pooling.setMaxConnectionsPerHost(HostDistance.REMOTE, 90);//maximum number of connections in the pool;

```
res query time : 25.88399839401245
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=5352e4be-ffdf-4f33-87f7-a98cbeb8df55, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (25102) or were cancelled (0), caused by Some fetches failed (25102) or were cancelled (0)'}]
```

* pooling.setMaxRequestsPerConnection(HostDistance.REMOTE, 256);// maximum number of requests per connection;
* pooling.setMaxConnectionsPerHost(HostDistance.REMOTE, 1);//maximum number of connections in the pool;

```json
res query time : 47.09238839149475
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=8c30ed2c-45db-416d-9516-55d89eaa47d9, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (78076) or were cancelled (0), caused by Some fetches failed (78076) or were cancelled (0)'}]
res query time : 27.72983145713806
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=8c30ed2c-45db-416d-9516-55d89eaa47d9, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (51072) or were cancelled (0), caused by Some fetches failed (51072) or were cancelled (0)'}]
```

* pooling.setMaxRequestsPerConnection(HostDistance.LOCAL, 256);// maximum number of requests per connection;
* pooling.setMaxRequestsPerConnection(HostDistance.REMOTE, 256);// maximum number of requests per connection;
* pooling.setMaxConnectionsPerHost(HostDistance.REMOTE, 100);//maximum number of connections in the pool;
* pooling.setMaxConnectionsPerHost(HostDistance.LOCAL, 100);//maximum number of connections in the pool;//pooling.setMaxQueueSize(10);
* pooling.setNewConnectionThreshold(HostDistance.REMOTE,50);

```json

res query time : 39.387837171554565
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=b3549e70-17ac-47de-a763-42beeaa47fd4, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (70933) or were cancelled (0), caused by Some fetches failed (70933) or were cancelled (0)'}]
```


* pooling.setMaxConnectionsPerHost(HostDistance.REMOTE, 100);//maximum number of connections in the pool;
* pooling.setMaxConnectionsPerHost(HostDistance.LOCAL, 100);//maximum number of connections in the pool;
* //pooling.setMaxQueueSize(10);
* pooling.setNewConnectionThreshold(HostDistance.REMOTE,50);
* pooling.setNewConnectionThreshold(HostDistance.LOCAL,50);
```json
res query time : 20.736347675323486
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=994c3f8f-512a-4d47-bfa2-36a4e815c5bf, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (14804) or were cancelled (0), caused by Some fetches failed (14804) or were cancelled (0)'}]
res query time : 40.3890483379364
[{'type': 'shard', 'nodes': ['LocalClusterNode(localMetadata=NodeMetadata(version=0, id=994c3f8f-512a-4d47-bfa2-36a4e815c5bf, tags={}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic)))'], 'shard': {}, 'error': 'Some fetches failed (74914) or were cancelled (0), caused by Some fetches failed (74914) or were cancelled (0)'}]

**Comment by udoprog** [comment]
Can you link to a branch where you have made the necessary modifications to apply these options?

Preferably it should be done through configuration, so the service doesn't have to be rebuilt when tweaking them.

**Comment by lucilecoutouly** [comment]
ok I am going to make it 

What am i looking is in always getting a responge from the server even if it take hours ...
have i to change the policy ? or something else ?

Thanks

**Comment by lucilecoutouly** [comment]
when i change parameters i have this issue : 
```
2017-09-14 10:00:02,839 DEBUG o.e.j.u.t.s.ExecuteProduceConsume [qtp2045913001-164] EPR Pend/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@65be5e31 run 
2017-09-14 10:00:02,839 DEBUG o.e.j.u.t.s.ExecuteProduceConsume [qtp2045913001-164] EPR Prod/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@65be5e31 produce enter 
2017-09-14 10:00:02,839 DEBUG o.e.j.u.t.s.ExecuteProduceConsume [qtp2045913001-164] EPR Prod/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@65be5e31 producing 
2017-09-14 10:00:02,839 DEBUG o.e.j.i.SelectChannelEndPoint [qtp2045913001-164] Key interests updated 1 -> 0 on SelectChannelEndPoint@2a44a6cd{/10.42.136.138:33444<->8080,Open,in,OSHUT,-,-,2/30000,HttpConnection}{io=0/0,kio=0,kro=1} 
2017-09-14 10:00:02,839 DEBUG o.e.j.i.ManagedSelector [qtp2045913001-164] Selector loop waiting on select 
2017-09-14 10:00:02,840 DEBUG o.e.j.i.ChannelEndPoint [qtp2045913001-28]  java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.eclipse.jetty.io.ChannelEndPoint.fill(ChannelEndPoint.java:145)
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:223)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

2017-09-14 10:00:02,841 DEBUG o.e.j.i.ChannelEndPoint [qtp2045913001-28] ishut SelectChannelEndPoint@2a44a6cd{/10.42.136.138:33444<->8080,Open,in,OSHUT,-,-,3/30000,HttpConnection}{io=0/0,kio=0,kro=1} 
```

what does it mean ?

**Comment by jcabmora** [comment]
@udoprog we have made this change (make Cassandra pooling options configurable) in our setup.  Do you think this is something you would be interested to be PR'd?

**Comment by udoprog** [comment]
@jcabmora Yes! Please set up a PR!

**Comment by jcabmora** [comment]
Hi @lucilecoutouly  and @udoprog ! I submitted this https://github.com/spotify/heroic/pull/371 . I'll appreciate any comments or suggestions.
