### ISSUE TITLE
heroic does not reconnect to elasticsearch seeds

### ISSUE THREAD

**Issue by memory** [spotify/heroic#477]
Scenario: 

- an elasticsearch cluster running behind an LB that round-robins connections between the three core nodes
- a heroic (0.9.0) cluster configured to use the elasticsearch metatdata backend, with the DNS name of the aforementioned LB provided as a seed and with node sniffing enabled:

```
    metadata:
      backends:
        - type: elasticsearch
          connection:
            clusterName: elasticsearch
            nodeClient: false
            sniff: true
            nodeSamplerInterval: 30s
            index:
              type: single
              index: heroic
            seeds:
              - elasticsearch-lb.default.svc.cluster.local
```

Expected behavior:

After a full restart of the elasticsearch cluster, the heroic cluster should re-connect to the seed address, discover the ES data nodes, and resume updating the ES index as new timeseries data is ingested.  Batch queries to heroic should be served successfully.

Observed behavior:

Batch queries fail; the following stacktrace is seen in the heroic logs.

```
20:02:36.498 [grpc-default-executor-9] ERROR com.spotify.heroic.rpc.grpc.GrpcRpcProtocolServer - 9bd77a4a-dbb8-46c5-a4d8-8b27b5a1c57a: Request failed
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{6H_WOi7pTTOtAzpCbd0EKw}{elasticsearch-lb.default.svc.cluster.local}{10.66.15.245:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:344)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:242)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:404)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at com.spotify.heroic.elasticsearch.AbstractElasticsearchMetadataBackend.scrollEntries(AbstractElasticsearchMetadataBackend.java:84)
	at com.spotify.heroic.metadata.elasticsearch.MetadataBackendKV.lambda$entries$18(MetadataBackendKV.java:413)
	at eu.toolchain.async.concurrent.ConcurrentManaged.doto(ConcurrentManaged.java:126)
	at com.spotify.heroic.metadata.elasticsearch.MetadataBackendKV.doto(MetadataBackendKV.java:490)
	at com.spotify.heroic.metadata.elasticsearch.MetadataBackendKV.entries(MetadataBackendKV.java:405)
	at com.spotify.heroic.metadata.elasticsearch.MetadataBackendKV.lambda$findSeries$8(MetadataBackendKV.java:294)
	at eu.toolchain.async.concurrent.ConcurrentManaged.doto(ConcurrentManaged.java:126)
	at com.spotify.heroic.metadata.elasticsearch.MetadataBackendKV.doto(MetadataBackendKV.java:490)
	at com.spotify.heroic.metadata.elasticsearch.MetadataBackendKV.findSeries(MetadataBackendKV.java:291)
	at com.spotify.heroic.statistics.semantic.SemanticMetadataBackendReporter$InstrumentedMetadataBackend.findSeries(SemanticMetadataBackendReporter.java:145)
	at com.spotify.heroic.metadata.MetadataBackendGroup.lambda$findSeries$2(MetadataBackendGroup.java:63)
	at com.spotify.heroic.metadata.MetadataBackendGroup.run(MetadataBackendGroup.java:136)
	at com.spotify.heroic.metadata.MetadataBackendGroup.findSeries(MetadataBackendGroup.java:63)
	at com.spotify.heroic.metric.LocalMetricManager$Group.protectedQuery(LocalMetricManager.java:340)
	at com.spotify.heroic.metric.LocalMetricManager$Group.query(LocalMetricManager.java:303)
	at com.spotify.heroic.rpc.grpc.GrpcRpcProtocol$GroupedQuery.apply(GrpcRpcProtocol.java:314)
	at com.spotify.heroic.rpc.grpc.GrpcRpcProtocolServer.lambda$setupContainer$2(GrpcRpcProtocolServer.java:114)
	at com.spotify.heroic.rpc.grpc.GrpcRpcContainer$1.handle(GrpcRpcContainer.java:44)
	at com.spotify.heroic.rpc.grpc.GrpcRpcProtocolServer.lambda$serverCallHandlerFor$17(GrpcRpcProtocolServer.java:230)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Note that the IP address that heroic has resolved for the LB is correct, and from a shell session on the heroic instance we can successfully query it:

```
root@heroic-0:/# curl -s 10.66.15.245:9200/_cluster/health
{
  "cluster_name": "elasticsearch",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 3,
  "number_of_data_nodes": 3,
  "active_primary_shards": 10,
  "active_shards": 20,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```

If (and only if) the heroic cluster is restarted, it will then successfully re-connect to elasticsearch and serve data.

**Comment by dmichel1** [comment]
@memory would it be possible to have the seed be the elasticsearch nodes themselves instead of going through a load balancer? That's how we run Heroic internally.

I believe you are running into similar issues described here, https://discuss.elastic.co/t/elasticsearch-cluster-with-aws-elb-randomly-disconnects-from-applications/133217/4

**Comment by memory** [comment]
That's actually the configuration that we started with, but because the ES nodes are part of a kubernetes cluster, we ran into a different problem: if the es data node pods restarted (e.g. to apply a config update), the k8s cluster could (and often would) reschedule them onto different machines where they would be assigned different IP addresses.  And the heroic elasticsearch client only resolves the seed DNS names at startup, so it would never see the new locations.

**Comment by dmichel1** [comment]
Did you have the ES nodes configured as a headless k8s service, with sniffing enabled? https://github.com/fabric8io/elasticsearch-cloud-kubernetes explains the setup a bit more

I'm thinking if you have the record produced by the k8s service along with sniffing enabled, this would handle the case of the k8s ES nodes being rescheduled. As long as the interval between the ES nodes is along enough so that a few ES nodes are still running. You could also try lowering the sniff interval if k8s isn't restarting things too quickly. You could also try tweaking the `minReadySeconds` as part of the k8s deployment to allow time for ES discovery to catch up.

Currently we run ES directly on GCE so havn't had much experience with this type of configuration.

**Comment by memory** [comment]
Okay, I'm happy to report back that this was mostly operator error in the end.  As you noted, ES (and for that matter heroic) needs a headless service configured in order for per-pod dns to be assigned and therefore for cluster discovery to work.  So we in fact had two services attached to our ES statefulset:

```
# the first, "headless" service provides per-pod dns for internal cluster
# autodiscovery to work
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    service: elasticsearch
spec:
  clusterIP: None
  ports:
  - port: 9200
    targetPort: 9200
    name: serving
  - port: 9300
    targetPort: 9300
    name: discovery
  selector:
    app: elasticsearch
# the second, ClusterIP service provides a (more) stable DNS address
# pointing to a cluster-level LB in front of the full group of ES nodes.
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
  labels:
    app: elasticsearch-lb
    service: elasticsearch-lb
spec:
  ports:
  - port: 9200
    targetPort: 9200
    name: serving
  selector:
    app: elasticsearch
```

You've probably already spotted the problem: the clusterip/lb service did not have the 9300/tcp configured, so the ES client was not able to query the cluster topology.  (Honestly I'm mystified as to why it ever worked at all.)

In an ideal world it would probably be best if `NoNodeAvailableException` were caught and it (possibly after some count of time) triggered a a rebuild of the ES client from scratch to avoid the case of a bad DNS->IP mapping being cached in perpetuity, but that may be well into I-want-a-pony territory. :)

**Comment by dmichel1** [comment]
We have some work to do in the coming months to migrate the es client from 5.x to 7.x. (or 8.x) as the transport client is be deprecated. When that work is being scoped out we can look at this problem more.

Right now at Spotify we aren't running any stateful workloads on GKE so this is all good information to have. Thanks!

https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients

**Comment by hexedpackets** [comment]
@dmichel1 What do you think we need to document related to this issue? Right now we don't really have any docs related to these kinds of deployment environment issues. Did you want to make something specific to deploying Elasticsearch in Kubernetes or were you thinking of something else?

**Comment by dmichel1** [comment]
@hexedpackets was thinking how we run ES internally with the separate masters and data nodes and the leanings in this issue about running ES on k8s.
