### ISSUE TITLE
Guava upgrade error

### ISSUE THREAD

**Issue by lmuhlha** [spotify/heroic#553]
https://github.com/spotify/heroic/pull/530
Introduced a runtime error from guava 28 upgrade:

[elasticsearch[_client_][listener][T#2]] ERROR com.spotify.heroic.HeroicService - Uncaught exception in thread Thread[elasticsearch[_client_][listener][T#2],5,main], exiting...

**Comment by hexedpackets** [comment]
Full stacktrace:

```
08:36:31.066 [elasticsearch[_client_][listener][T#2]] ERROR com.spotify.heroic.HeroicService - Uncaught exception in thread Thread[elasticsearch[_client_][listener][T#2],5,main], exiting...
java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.transform(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/base/Function;)Lcom/google/common/util/concurrent/ListenableFuture;
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.readFlatRowsAsync(BigtableDataGrpcClient.java:356)
	at com.spotify.heroic.metric.bigtable.api.BigtableDataClientImpl.readRows(BigtableDataClientImpl.java:83)
	at com.spotify.heroic.metric.bigtable.BigtableBackend.fetchBatch(BigtableBackend.java:443)
	at com.spotify.heroic.metric.bigtable.BigtableBackend.lambda$fetch$14(BigtableBackend.java:279)
	at eu.toolchain.async.concurrent.ConcurrentManaged.doto(ConcurrentManaged.java:126)
	at com.spotify.heroic.metric.bigtable.BigtableBackend.fetch(BigtableBackend.java:270)
	at com.spotify.heroic.statistics.semantic.SemanticMetricBackendReporter$InstrumentedMetricBackend.fetch(SemanticMetricBackendReporter.java:243)
	at com.spotify.heroic.metric.LocalMetricManager$Group$Transform.lambda$null$4(LocalMetricManager.java:289)
	at eu.toolchain.async.TinyAsync.doEventuallyCollectImmediate(TinyAsync.java:409)
	at eu.toolchain.async.TinyAsync.eventuallyCollect(TinyAsync.java:366)
	at com.spotify.heroic.metric.LocalMetricManager$Group$Transform.transform(LocalMetricManager.java:295)
	at com.spotify.heroic.metric.LocalMetricManager$Group$Transform.transform(LocalMetricManager.java:176)
	at eu.toolchain.async.helper.ResolvedLazyTransformHelper.resolved(ResolvedLazyTransformHelper.java:24)
	at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
	at eu.toolchain.async.RecursionSafeAsyncCaller.lambda$resolve$0(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.RecursionSafeAsyncCaller.execute(RecursionSafeAsyncCaller.java:99)
	at eu.toolchain.async.RecursionSafeAsyncCaller.resolve(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture$2.run(ConcurrentResolvableFuture.java:238)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.run(ConcurrentResolvableFuture.java:458)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.resolve(ConcurrentResolvableFuture.java:105)
	at eu.toolchain.async.helper.CollectHelper.done(CollectHelper.java:175)
	at eu.toolchain.async.helper.CollectHelper.add(CollectHelper.java:143)
	at eu.toolchain.async.helper.CollectHelper.resolved(CollectHelper.java:81)
	at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
	at eu.toolchain.async.RecursionSafeAsyncCaller.lambda$resolve$0(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.RecursionSafeAsyncCaller.execute(RecursionSafeAsyncCaller.java:99)
	at eu.toolchain.async.RecursionSafeAsyncCaller.resolve(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture$2.run(ConcurrentResolvableFuture.java:238)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.run(ConcurrentResolvableFuture.java:458)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.resolve(ConcurrentResolvableFuture.java:105)
	at eu.toolchain.async.helper.ResolvedTransformHelper.resolved(ResolvedTransformHelper.java:29)
	at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
	at eu.toolchain.async.RecursionSafeAsyncCaller.lambda$resolve$0(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.RecursionSafeAsyncCaller.execute(RecursionSafeAsyncCaller.java:99)
	at eu.toolchain.async.RecursionSafeAsyncCaller.resolve(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture$2.run(ConcurrentResolvableFuture.java:238)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.run(ConcurrentResolvableFuture.java:458)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.resolve(ConcurrentResolvableFuture.java:105)
	at eu.toolchain.async.helper.ResolvedLazyTransformHelper$1.resolved(ResolvedLazyTransformHelper.java:38)
	at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
	at eu.toolchain.async.RecursionSafeAsyncCaller.lambda$resolve$0(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.RecursionSafeAsyncCaller.execute(RecursionSafeAsyncCaller.java:99)
	at eu.toolchain.async.RecursionSafeAsyncCaller.resolve(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture$2.run(ConcurrentResolvableFuture.java:238)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.run(ConcurrentResolvableFuture.java:458)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.resolve(ConcurrentResolvableFuture.java:105)
	at eu.toolchain.async.helper.ResolvedLazyTransformHelper$1.resolved(ResolvedLazyTransformHelper.java:38)
	at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
	at eu.toolchain.async.RecursionSafeAsyncCaller.lambda$resolve$0(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.RecursionSafeAsyncCaller.execute(RecursionSafeAsyncCaller.java:99)
	at eu.toolchain.async.RecursionSafeAsyncCaller.resolve(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.immediate.ImmediateResolvedAsyncFuture.onDone(ImmediateResolvedAsyncFuture.java:59)
	at eu.toolchain.async.helper.ResolvedLazyTransformHelper.resolved(ResolvedLazyTransformHelper.java:30)
	at eu.toolchain.async.DirectAsyncCaller.resolve(DirectAsyncCaller.java:10)
	at eu.toolchain.async.RecursionSafeAsyncCaller.lambda$resolve$0(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.RecursionSafeAsyncCaller.execute(RecursionSafeAsyncCaller.java:99)
	at eu.toolchain.async.RecursionSafeAsyncCaller.resolve(RecursionSafeAsyncCaller.java:37)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture$2.run(ConcurrentResolvableFuture.java:238)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.run(ConcurrentResolvableFuture.java:458)
	at eu.toolchain.async.concurrent.ConcurrentResolvableFuture.resolve(ConcurrentResolvableFuture.java:105)
	at com.spotify.heroic.elasticsearch.AbstractElasticsearchBackend$1.onResponse(AbstractElasticsearchBackend.java:50)
	at com.spotify.heroic.elasticsearch.AbstractElasticsearchBackend$1.onResponse(AbstractElasticsearchBackend.java:47)
	at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:98)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

> Task :heroic-dist:HeroicService.main() FAILED
```
