### ISSUE TITLE
Unhandled exception caught in core executor java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback

### ISSUE THREAD

**Issue by Petee87** [spotify/heroic#601]
Hi,

I try to use cassandra as metrics backend for heroic 1.0.1, but I got error:
```
2020-02-10 13:40:21,076 INFO c.d.d.c.GuavaCompatibility [heroic-core-2] Detected Guava < 19 in the classpath, using legacy compatibility layer 
2020-02-10 13:40:21,076 ERROR c.s.h.HeroicCore [heroic-core-2] Unhandled exception caught in core executor java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
        at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:136)
        at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:52)
        at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:68)
        at com.spotify.heroic.metric.datastax.ManagedSetupConnection.lambda$construct$0(ManagedSetupConnection.java:86)
        at eu.toolchain.async.TinyAsync$2.run(TinyAsync.java:218)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 10 more

2020-02-10 13:40:21,071 DEBUG o.e.j.u.t.QueuedThreadPool [qtp2142581334-26] Runner started for QueuedThreadPool[qtp2142581334]@7fb53256{STARTING,8<=8<=200,i=8,r=-1,q=0}[ReservedThreadExecutor@19d548e6{s=0/2,p=0}] 
2020-02-10 13:40:21,076 ERROR c.s.h.HeroicCore [heroic-core-2] Unhandled exception caught in core executor java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
        at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:136)
        at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:52)
        at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:68)
        at com.spotify.heroic.metric.datastax.ManagedSetupConnection.lambda$construct$0(ManagedSetupConnection.java:86)
        at eu.toolchain.async.TinyAsync$2.run(TinyAsync.java:218)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 10 more

2020-02-10 13:40:21,078 ERROR c.s.h.HeroicCore [heroic-core-2] Exiting (code=2) 
2020-02-10 13:40:21,078 ERROR c.s.h.HeroicCore [heroic-core-2] Exiting (code=2) 
```

**Comment by hexedpackets** [comment]
This is happening because we updated the version of Guava in Heroic. Unfortunately, the way its loaded causes runtime errors instead of being caught during the build and this code path isn't hit during the tests.

I think our options are to either shade an older version of guava inside the cassandra module, or update cassandra to be compatible with the newer guava. No idea how much effort the latter is - it would almost certainly involve updating the datastax library and not just Heroic code.

**Comment by hexedpackets** [comment]
@Petee87 This should be fixed in 1.0.2, which is being pushed out now. Thanks for reporting!

**Comment by Petee87** [comment]
@hexedpackets You are very welcome!

**Comment by Petee87** [comment]
@hexedpackets Are you planning long term support for Cassandra backend?

**Comment by hexedpackets** [comment]
@Petee87 Internally we use the Bigtable backend but we plan to keep supporting non-GCP backends, including Cassandra . We've been discussing how to improve our system testing so we can maintain the modules that we aren't using day-to-day - having these seemingly easy to catch bugs is definitely not ok.
