### ISSUE TITLE
Unhandled exception caught in core executor java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter

### ISSUE THREAD

**Issue by Petee87** [spotify/heroic#607]
Hi,

After the datastax driver upgrade, I wanted to try out the heroic-1.0.2 with C*, but I got a newer error:
```
2020-02-12 10:02:55,379 ERROR c.s.h.HeroicCore [heroic-core-2] Unhandled exception caught in core executor java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter
        at com.datastax.driver.core.Metrics.<init>(Metrics.java:146)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1667)
        at com.datastax.driver.core.Cluster.init(Cluster.java:214)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:387)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:366)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:311)
        at com.spotify.heroic.metric.datastax.ManagedSetupConnection.lambda$construct$0(ManagedSetupConnection.java:97)
        at eu.toolchain.async.TinyAsync$2.run(TinyAsync.java:218)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.JmxReporter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 13 more

2020-02-12 10:02:55,379 ERROR c.s.h.HeroicCore [heroic-core-2] Unhandled exception caught in core executor java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter
        at com.datastax.driver.core.Metrics.<init>(Metrics.java:146)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1667)
        at com.datastax.driver.core.Cluster.init(Cluster.java:214)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:387)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:366)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:311)
        at com.spotify.heroic.metric.datastax.ManagedSetupConnection.lambda$construct$0(ManagedSetupConnection.java:97)
        at eu.toolchain.async.TinyAsync$2.run(TinyAsync.java:218)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.JmxReporter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 13 more

2020-02-12 10:02:55,382 ERROR c.s.h.HeroicCore [heroic-core-2] Exiting (code=2) 
2020-02-12 10:02:55,382 ERROR c.s.h.HeroicCore [heroic-core-2] Exiting (code=2)

**Comment by hexedpackets** [comment]
@Petee87 Can you share the config you're starting Heroic with? I have an idea of what's causing this, but your config will help me pin it down.

**Comment by Petee87** [comment]
@hexedpackets It's my heroic config:
```
port: 8080

cluster:
  tags:
    site: london

metrics:
  backends:
    - type: datastax
      seeds:
        - 192.168.0.1:9042

metadata:
  backends:
    - type: memory

suggest:
  backends:
    - type: memory

statistics:
  type: semantic

shellServer:
  port: 9192
